language: python
os:
  - linux
sudo: false
env:
  matrix:
    - PYTHON_VERSION="2.7"
    - PYTHON_VERSION="3.6"
    - PYTHON_VERSION="3.7"
  global:
    - PATH=${HOME}/miniconda/bin:${PATH}
    - LD_LIBRARY_PATH=${HOME}/miniconda/lib
    - PYCTEST_ARGS='--pyctest-submit --pyctest-jobs=1 --pyctest-site=Travis'
before_install:
  - if [[ "$PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p ${HOME}/miniconda
  - export PATH="${HOME}/miniconda/bin:${PATH}"
  - conda config --set always_yes yes
install:
  - conda config --add channels jrmadsen
  - conda config --add channels conda-forge
  - if [[ "$PYTHON_VERSION" == "2.7" ]]; then
      conda install python=$PYTHON_VERSION
      --file envs/requirements-all.txt
      --file envs/requirements-unix-build.txt
      --file envs/requirements-py27.txt;
    else
      conda install python=$PYTHON_VERSION python-coveralls
      --file envs/requirements-all.txt
      --file envs/requirements-unix-build.txt
      --file envs/requirements-bench.txt;
    fi;
  - conda info -a
  - conda list --explicit
  - if [[ "$PYTHON_VERSION" == "2.7" ]]; then
      python setup.py install;
    else
      python -m benchmarking --disable-phantom-tests ${PYCTEST_ARGS} -- -VV;
    fi;
script:
  - if [[ "$PYTHON_VERSION" == "2.7" ]]; then
      nosetests;
    fi;
after_success:
  - coveralls
